- name: Install Java {{java_version}} RedHat
  package:
    name:
    - java-1.{{java_version}}.0-openjdk-devel
    state: present

- name: install libselinux-python package if we need to register env vars
  yum: name=libselinux-python state=present
  when: java_register_env
